### ISSUE TITLE
No description or SFZ for the Pettinhouse Yamaha Kit

### ISSUE THREAD

**Issue by shivpalkang** [sfzinstruments/mappings#3]
Right now the Readme is empty
> https://github.com/sfzinstruments/mappings/tree/master/Pettinhouse%20Yamaha%20Kit%20Free

Is the SFZ for this kit available somewhere?
I checked the KVR forums and SWTrex seems to have made one in 2006

> https://www.kvraudio.com/forum/viewtopic.php?f=42&t=130251&start=30#top

but all the links are long gone.
And I checked this:
>http://www.drealm.info/sfz/K-v-R/SWTrex.html

But the SFZ for this kit isn't hosted there either.
I'd like to know if an sfz for this exists somewhere, if not I'd be glad to make one, and it would be my first one.

**Comment by kinwie** [comment]
Hi, I added the Pettinhouse Yamaha 9000 drumkit in this repo. Hope it'll useful for you. Cheers!

**Comment by kinwie** [comment]
I misread your post, thought you requested the sfz file.
But anyway, the sfz for it had been created in this repo, so I close this now
