### ISSUE TITLE
how does one submit a new instument?

### ISSUE THREAD

**Issue by squinkylabs** [sfzinstruments/mappings#4]
In general, I see that an instrument with samples is its own repo under sfzinstruments.

What is the mechanism by which "outsiders" can submit instruments? (I have to confess I don't know that much about pull requests).

**Comment by kinwie** [comment]
You can contact @redtide or @DSmolken for more details

**Comment by DSmolken** [comment]
Yeah, kinwie's right - just ask us to create a repo and give you full rights to that repo. You can ask either here or on the Discord, all we really need to know is what the repo name should be. One repo per instrument is fine, or you could have one repo for multiple instruments and have each instrument in a separate folder, whichever you prefer. Sorry I didn't see this earlier.

**Comment by redtide** [comment]
I think a more straightforward way should be to create an own repository and request later, once complete, to be transferred.

**Comment by squinkylabs** [comment]
ah, makes sense. tx!
